export const ADD_PROJECTS = "ADD_PROJECTS";
export const PROJECTS_FAILED = "PROJECTS_FAILED";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const TOGGLE = "TOGGLE";
export const SENDMESSAGE = "SENDMESSAGE";
